apiVersion: cert-manager.io/v1
kind: CertificateRequest
metadata:
  name: ${GLOO_GATEWAY_PROXY_IP}.nip.io
  namespace: step-certificates-system
spec:
  # The base64 encoded version of the certificate request in PEM format.
  request: ${GLOO_DEMOS_CSR}
  # The duration of the certificate
  duration: 24h
  # A reference to the issuer in charge of signing the CSR.
  issuerRef:
    group: certmanager.step.sm
    kind: StepIssuer
    name: step-issuer
