apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: oidc-dex
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        appUrl: https://$GLOO_GATEWAY_PROXY_IP.nip.io
        callbackPath: /callback
        clientId: fruits-app
        clientSecretRef:
          name: fruits-app-oauth
          namespace: gloo-system
        issuerUrl: https://$DEX_SERVER_IP.nip.io/
        scopes:
        - email
        session:
          cookieOptions:
            notSecure: true

