apiVersion: apps/v1
kind: Deployment
metadata:
  name: extauth
  namespace: gloo-system
spec:
  template:
    spec:
      volumes:
        - name: certs
          emptyDir: {}
        - name: ca-certs
          secret:
            secretName: trusted-ca
            items:
              - key: tls.crt
                path: ca.crt
      containers:
      - name: fruits-app-ui
        image: "${GLOO_EE_IMAGE}"
        volumeMounts:
          - mountPath: /etc/ssl/certs/
            name: certs
      initContainers:
        - name: add-ca-cert
          image: "${GLOO_EE_IMAGE}"
          command:
            - "sh"
          args:
            - "-c"
            - "cp -r /etc/ssl/certs/* /certs; cat /etc/ssl/certs/ca-certificates.crt /ca-certs/ca.crt > /certs/ca-certificates.crt"
          volumeMounts:
            - mountPath: /certs
              name: certs
            - mountPath: /ca-certs
              name: ca-certs