apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca
spec:
  selector:
    matchLabels:
      app: ca
  template:
    metadata:
      labels:
        app: ca
    spec:
      initContainers:
      - name: step-ca-init
        image: ghcr.io/kameshsampath/gloo-demos-acme-ca
        env:
          - name: DNS_NAMES
            valueFrom:
              configMapKeyRef:
                name: ca-init-config
                key: dnsNames
          - name: PROVISIONER_NAME
            valueFrom:
              configMapKeyRef:
                name: ca-init-config
                key: provisionerName
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        command:
          - "step"
        args:
          - "ca"
          - "init"
          - '--name="My Gloo Minikube Demos"'
          - "--dns=$(DNS_NAMES),$(HOST_IP).nip.io,ca-$(HOST_IP).nip.io,$(HOST_IP)"
          - "--address=:8443"
          - "--provisioner=$(PROVISIONER_NAME)"
          - "--password-file=/home/user/step/password"
          - "--provisioner-password-file=/home/user/step/password"
        volumeMounts:
          - mountPath: /home/user/step
            name: ca-password-file
          - mountPath: /home/user/.step
            name: step-path
      - name: step-ca-acme-provisioner
        image: ghcr.io/kameshsampath/gloo-demos-acme-ca
        command:
          - step
        args:
          - ca
          - provisioner
          - add
          - acme
          - "--type"
          - "ACME"
        volumeMounts:
          - mountPath: /home/user/step
            name: ca-password-file
          - mountPath: /home/user/.step
            name: step-path
      containers:
      - name: ca
        image: ghcr.io/kameshsampath/gloo-demos-acme-ca
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        command:
          - "step-ca"
        args:
          - "--password-file=/home/user/step/password"
          - "/home/user/.step/config/ca.json"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: https
          containerPort: 8443
        volumeMounts:
          - mountPath: /home/user/step
            name: ca-password-file
          - mountPath: /home/user/.step
            name: step-path
      volumes:
        - name: step-path
          persistentVolumeClaim:
            claimName: step-path-pvc
        - name: ca-password-file
          secret:
            secretName: password-file
