namespace: my-acme-ca

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ca-init-config
    literals:
      - dnsNames="ca.my-acme-ca.svc.cluster.local"
      - provisionerName="mygloodemos@example.com"

secretGenerator:
  - name: password-file
    literals:
      - password="password"

resources:
 - pvc.yaml
 - namespace.yaml
 - deployment.yaml
 - service.yaml
