issuer: https://dex-${MINIKUBE_IP}.nip.io:32000
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  https: 0.0.0.0:5556
  tlsCert: /etc/dex/tls/tls.crt
  tlsKey: /etc/dex/tls/tls.key
connectors:
- type: github
  id: github
  name: GitHub
  config:
    clientID: $GH_OAUTH_CLIENT_ID
    clientSecret: $GH_OAUTH_CLIENT_SECRET
    redirectURI: https://dex-${MINIKUBE_IP}.nip.io:32000/callback
    org: $GITHUB_ORG
oauth2:
  skipApprovalScreen: false
staticClients:
- id: fruits-app
  redirectURIs:
  - 'http://$MINIKUBE_IP.nip.io:30443/callback'
  name: 'Fruits App'
  # value is fruits-app-secret
  secret: nJ1aXRzLWFwcC1zZWNyZXQ=
enablePasswordDB: true
staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
