issuer: https://${DEX_SERVER_IP}.nip.io
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  https: 0.0.0.0:5556
  tlsCert: /etc/dex/tls/tls.crt
  tlsKey: /etc/dex/tls/tls.key
# TODO enable later
# connectors:
# - type: github
#   id: github
#   name: GitHub
#   config:
#     clientID: $GH_OAUTH_CLIENT_ID
#     clientSecret: $GH_OAUTH_CLIENT_SECRET
#     redirectURI: https://${DEX_SERVER_IP}.nip.io/callback
#     org: $GITHUB_ORG
# oauth2:
#   skipApprovalScreen: false
staticClients:
- id: fruits-app
  redirectURIs:
  - 'https://${GLOO_GATEWAY_PROXY_IP}.nip.io/callback'
  name: 'Fruits App'
  # value is fruits-app-secret base64 encoded
  secret: ZnJ1aXRzLWFwcC1zZWNyZXQK
enablePasswordDB: true
staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
