namespace: dex

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: github-client
    envs:
     - github.env.secret
  - name: dex-tls
    files:
      - tls.crt=../../certs/gloo-demos.crt
      - tls.key=../../certs/gloo-demos-key.pem
      - ca.crt=../../certs/gloo-demos-ca.crt
configMapGenerator:
  - name: dex
    files:
      - config.yaml
resources:
  - namespace.yaml
  - sa.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
