namespace: dex

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: github-client
    envs:
     - github.env.secret
configMapGenerator:
  - name: dex
    files:
      - config.yaml
resources:
  - sa.yaml
  - rbac.yaml
  - deployment.yaml
